services:
  oracle:
    image: gvenzl/oracle-free:latest
    container_name: testpilot-oracle
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: Bk.25122512
    volumes:
      - oracle-data:/opt/oracle/oradata

volumes:
  oracle-data:
