-- ============================================================================
-- LDAP Ayarları Tablosu ve Test Verileri
-- Bu script MOBILE_LDAP_SETTINGS tablosunu oluşturur ve test eder
-- ============================================================================

-- 1. Tabloyu oluştur (eğer yoksa)
CREATE TABLE MOBILE_LDAP_SETTINGS (
    ID                       NUMBER(10)  DEFAULT 1 NOT NULL,
    URL                      VARCHAR2(500),
    BASE_DN                  VARCHAR2(500),
    MANAGER_DN               VARCHAR2(500),
    MANAGER_PASSWORD_ENCRYPTED VARCHAR2(1000),
    USER_DN_PATTERN          VARCHAR2(500),
    USER_SEARCH_FILTER       VARCHAR2(500),
    GROUP_SEARCH_BASE        VARCHAR2(500),
    GROUP_SEARCH_FILTER      VARCHAR2(500),
    PASSWORD_ENCODER_TYPE    VARCHAR2(50) DEFAULT 'bcrypt',
    CONSTRAINT PK_MOBILE_LDAP_SETTINGS PRIMARY KEY (ID),
    CONSTRAINT CK_MOBILE_LDAP_SETTINGS_ID CHECK (ID = 1)
);

COMMENT ON TABLE MOBILE_LDAP_SETTINGS IS 'LDAP yapılandırma ayarları (tek satır, ID=1)';
COMMENT ON COLUMN MOBILE_LDAP_SETTINGS.MANAGER_PASSWORD_ENCRYPTED IS 'AES ile şifrelenmiş manager şifresi';
COMMENT ON COLUMN MOBILE_LDAP_SETTINGS.PASSWORD_ENCODER_TYPE IS 'Kullanıcı şifreleme algoritması (bcrypt, sha256, etc.)';

-- 2. Varsayılan kayıt ekle (eğer yoksa)
MERGE INTO MOBILE_LDAP_SETTINGS target
USING DUAL
ON (target.ID = 1)
WHEN NOT MATCHED THEN
    INSERT (ID, URL, BASE_DN, MANAGER_DN, MANAGER_PASSWORD_ENCRYPTED, 
            USER_DN_PATTERN, USER_SEARCH_FILTER, GROUP_SEARCH_BASE, 
            GROUP_SEARCH_FILTER, PASSWORD_ENCODER_TYPE)
    VALUES (1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'bcrypt');

-- 3. Mevcut kaydı kontrol et
SELECT 'MOBILE_LDAP_SETTINGS tablosu kontrolü:' AS INFO FROM DUAL
UNION ALL
SELECT 'ID: ' || ID FROM MOBILE_LDAP_SETTINGS WHERE ID = 1
UNION ALL
SELECT 'URL: ' || URL FROM MOBILE_LDAP_SETTINGS WHERE ID = 1
UNION ALL
SELECT 'BASE_DN: ' || BASE_DN FROM MOBILE_LDAP_SETTINGS WHERE ID = 1
UNION ALL
SELECT 'MANAGER_DN: ' || MANAGER_DN FROM MOBILE_LDAP_SETTINGS WHERE ID = 1
UNION ALL
SELECT 'USER_DN_PATTERN: ' || USER_DN_PATTERN FROM MOBILE_LDAP_SETTINGS WHERE ID = 1
UNION ALL
SELECT 'USER_SEARCH_FILTER: ' || USER_SEARCH_FILTER FROM MOBILE_LDAP_SETTINGS WHERE ID = 1
UNION ALL
SELECT 'PASSWORD_ENCODER_TYPE: ' || PASSWORD_ENCODER_TYPE FROM MOBILE_LDAP_SETTINGS WHERE ID = 1;

-- 4. Test verisi ekle (LDAP ayarlarını test etmek için)
MERGE INTO MOBILE_LDAP_SETTINGS target
USING DUAL
ON (target.ID = 1)
WHEN MATCHED THEN
    UPDATE SET 
        URL = 'ldap://localhost:389',
        BASE_DN = 'dc=company,dc=com',
        MANAGER_DN = 'cn=admin,dc=company,dc=com',
        MANAGER_PASSWORD_ENCRYPTED = 'test_encrypted_password',
        USER_DN_PATTERN = 'uid={0},ou=people',
        USER_SEARCH_FILTER = '(uid={0})',
        GROUP_SEARCH_BASE = 'ou=groups,dc=company,dc=com',
        GROUP_SEARCH_FILTER = 'memberUid={0}',
        PASSWORD_ENCODER_TYPE = 'bcrypt';

-- 5. Güncellenmiş veriyi kontrol et
SELECT 'GÜNCELLENMİŞ LDAP AYARLARI:' AS INFO FROM DUAL
UNION ALL
SELECT 'URL: ' || URL FROM MOBILE_LDAP_SETTINGS WHERE ID = 1
UNION ALL
SELECT 'BASE_DN: ' || BASE_DN FROM MOBILE_LDAP_SETTINGS WHERE ID = 1
UNION ALL
SELECT 'MANAGER_DN: ' || MANAGER_DN FROM MOBILE_LDAP_SETTINGS WHERE ID = 1
UNION ALL
SELECT 'USER_DN_PATTERN: ' || USER_DN_PATTERN FROM MOBILE_LDAP_SETTINGS WHERE ID = 1
UNION ALL
SELECT 'USER_SEARCH_FILTER: ' || USER_SEARCH_FILTER FROM MOBILE_LDAP_SETTINGS WHERE ID = 1
UNION ALL
SELECT 'GROUP_SEARCH_BASE: ' || GROUP_SEARCH_BASE FROM MOBILE_LDAP_SETTINGS WHERE ID = 1
UNION ALL
SELECT 'GROUP_SEARCH_FILTER: ' || GROUP_SEARCH_FILTER FROM MOBILE_LDAP_SETTINGS WHERE ID = 1
UNION ALL
SELECT 'PASSWORD_ENCODER_TYPE: ' || PASSWORD_ENCODER_TYPE FROM MOBILE_LDAP_SETTINGS WHERE ID = 1;

-- 6. Tablo yapısını kontrol et
SELECT COLUMN_NAME, DATA_TYPE, DATA_LENGTH, NULLABLE
FROM USER_TAB_COLUMNS
WHERE TABLE_NAME = 'MOBILE_LDAP_SETTINGS'
ORDER BY COLUMN_ID;